### ISSUE TITLE
How can the version number of the mmtf-java library be accessed programmatically?

### ISSUE THREAD

**Issue by pwrose** [rcsb/mmtf-java#35]
A user, who used the .jar files directly, wants to get the version number of the mmtf-java library.

**Comment by josemduarte** [comment]
What about using `StructureDataInterface.getMmtfVersion()` ?

**Comment by pwrose** [comment]
The user was trying to get the version of the mmtf-java library, rather
than the mmtf version of the file, which is what
StructureDataInterface.getMmtfVersion() returns.

**Comment by josemduarte** [comment]
Oh I see. Well all jar files that we publish have the version in their names, that's how one would usually find out.

In any case I don't think it's possible to do it programmatically at the moment. It would have to be implemented. It can be done like this: http://stackoverflow.com/questions/3697449/retrieve-version-from-maven-pom-xml-in-code

**Comment by abradle** [comment]
Closing this. Jose's solution looks good.
